var searchData=
[
  ['dailyboostervaccinations_2179',['DailyBoosterVaccinations',['../structmio_1_1osecirts_1_1DailyBoosterVaccinations.html',1,'mio::osecirts']]],
  ['dailyfullvaccinations_2180',['DailyFullVaccinations',['../structmio_1_1osecirts_1_1DailyFullVaccinations.html',1,'mio::osecirts::DailyFullVaccinations&lt; FP &gt;'],['../structmio_1_1osecirvvs_1_1DailyFullVaccinations.html',1,'mio::osecirvvs::DailyFullVaccinations&lt; FP &gt;']]],
  ['dailypartialvaccinations_2181',['DailyPartialVaccinations',['../structmio_1_1osecirts_1_1DailyPartialVaccinations.html',1,'mio::osecirts::DailyPartialVaccinations&lt; FP &gt;'],['../structmio_1_1osecirvvs_1_1DailyPartialVaccinations.html',1,'mio::osecirvvs::DailyPartialVaccinations&lt; FP &gt;']]],
  ['damping_2182',['Damping',['../classmio_1_1Damping.html',1,'mio']]],
  ['dampingmatrixexpression_2183',['DampingMatrixExpression',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpression_3c_20squaredampings_20_3e_2184',['DampingMatrixExpression&lt; SquareDampings &gt;',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpression_3c_20vectordampings_20_3e_2185',['DampingMatrixExpression&lt; VectorDampings &gt;',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_2186',['DampingMatrixExpressionGroup',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_3c_20contactmatrix_20_3e_2187',['DampingMatrixExpressionGroup&lt; ContactMatrix &gt;',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_3c_20mobilitycoefficients_20_3e_2188',['DampingMatrixExpressionGroup&lt; MobilityCoefficients &gt;',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampings_2189',['Dampings',['../classmio_1_1Dampings.html',1,'mio']]],
  ['dampingsampling_2190',['DampingSampling',['../classmio_1_1DampingSampling.html',1,'mio']]],
  ['dampingsampling_3c_20double_20_3e_2191',['DampingSampling&lt; double &gt;',['../classmio_1_1DampingSampling.html',1,'mio']]],
  ['datawritertomemory_2192',['DataWriterToMemory',['../structmio_1_1DataWriterToMemory.html',1,'mio']]],
  ['datawritertomemorydelta_2193',['DataWriterToMemoryDelta',['../structmio_1_1abm_1_1DataWriterToMemoryDelta.html',1,'mio::abm']]],
  ['date_2194',['Date',['../structmio_1_1Date.html',1,'mio']]],
  ['daysuntileffectiveboosterimmunity_2195',['DaysUntilEffectiveBoosterImmunity',['../structmio_1_1osecirts_1_1DaysUntilEffectiveBoosterImmunity.html',1,'mio::osecirts']]],
  ['daysuntileffectiveimprovedimmunity_2196',['DaysUntilEffectiveImprovedImmunity',['../structmio_1_1osecirvvs_1_1DaysUntilEffectiveImprovedImmunity.html',1,'mio::osecirvvs']]],
  ['daysuntileffectiveimprovedvaccination_2197',['DaysUntilEffectiveImprovedVaccination',['../structmio_1_1osecirts_1_1DaysUntilEffectiveImprovedVaccination.html',1,'mio::osecirts']]],
  ['daysuntileffectivepartialimmunity_2198',['DaysUntilEffectivePartialImmunity',['../structmio_1_1osecirvvs_1_1DaysUntilEffectivePartialImmunity.html',1,'mio::osecirvvs']]],
  ['daysuntileffectivepartialvaccination_2199',['DaysUntilEffectivePartialVaccination',['../structmio_1_1osecirts_1_1DaysUntilEffectivePartialVaccination.html',1,'mio::osecirts']]],
  ['deathrate_2200',['DeathRate',['../structmio_1_1oseair_1_1DeathRate.html',1,'mio::oseair']]],
  ['deathspercritical_2201',['DeathsPerCritical',['../structmio_1_1lsecir_1_1DeathsPerCritical.html',1,'mio::lsecir::DeathsPerCritical'],['../structmio_1_1osecir_1_1DeathsPerCritical.html',1,'mio::osecir::DeathsPerCritical&lt; FP &gt;'],['../structmio_1_1osecirts_1_1DeathsPerCritical.html',1,'mio::osecirts::DeathsPerCritical&lt; FP &gt;'],['../structmio_1_1osecirvvs_1_1DeathsPerCritical.html',1,'mio::osecirvvs::DeathsPerCritical&lt; FP &gt;']]],
  ['defaultfactory_2202',['DefaultFactory',['../structmio_1_1DefaultFactory.html',1,'mio']]],
  ['defaultfactory_3c_20abm_3a_3amask_20_3e_2203',['DefaultFactory&lt; abm::Mask &gt;',['../structmio_1_1DefaultFactory_3_01abm_1_1Mask_01_4.html',1,'mio']]],
  ['defaultfactory_3c_20abm_3a_3aperson_20_3e_2204',['DefaultFactory&lt; abm::Person &gt;',['../structmio_1_1DefaultFactory_3_01abm_1_1Person_01_4.html',1,'mio']]],
  ['defaultfactory_3c_20abm_3a_3aprotectionevent_20_3e_2205',['DefaultFactory&lt; abm::ProtectionEvent &gt;',['../structmio_1_1DefaultFactory_3_01abm_1_1ProtectionEvent_01_4.html',1,'mio']]],
  ['defaultfactory_3c_20abm_3a_3atrip_20_3e_2206',['DefaultFactory&lt; abm::Trip &gt;',['../structmio_1_1DefaultFactory_3_01abm_1_1Trip_01_4.html',1,'mio']]],
  ['dereffunctor_2207',['DerefFunctor',['../structmio_1_1details_1_1DerefFunctor.html',1,'mio::details']]],
  ['detectinfection_2208',['DetectInfection',['../structmio_1_1abm_1_1DetectInfection.html',1,'mio::abm']]],
  ['disjunction_2209',['disjunction',['../structmio_1_1disjunction.html',1,'mio']]],
  ['disjunction_3c_20b1_20_3e_2210',['disjunction&lt; B1 &gt;',['../structmio_1_1disjunction_3_01B1_01_4.html',1,'mio']]],
  ['disjunction_3c_20b1_2c_20bn_2e_2e_2e_20_3e_2211',['disjunction&lt; B1, Bn... &gt;',['../structmio_1_1disjunction_3_01B1_00_01Bn_8_8_8_01_4.html',1,'mio']]],
  ['dynamicnpis_2212',['DynamicNPIs',['../classmio_1_1DynamicNPIs.html',1,'mio']]],
  ['dynamicnpis_3c_20scalartype_20_3e_2213',['DynamicNPIs&lt; ScalarType &gt;',['../classmio_1_1DynamicNPIs.html',1,'mio']]],
  ['dynamicnpisimplementationdelay_2214',['DynamicNPIsImplementationDelay',['../structmio_1_1osecir_1_1DynamicNPIsImplementationDelay.html',1,'mio::osecir::DynamicNPIsImplementationDelay&lt; FP &gt;'],['../structmio_1_1osecirts_1_1DynamicNPIsImplementationDelay.html',1,'mio::osecirts::DynamicNPIsImplementationDelay&lt; FP &gt;'],['../structmio_1_1osecirvvs_1_1DynamicNPIsImplementationDelay.html',1,'mio::osecirvvs::DynamicNPIsImplementationDelay&lt; FP &gt;']]],
  ['dynamicnpisinfectedsymptoms_2215',['DynamicNPIsInfectedSymptoms',['../structmio_1_1osecir_1_1DynamicNPIsInfectedSymptoms.html',1,'mio::osecir::DynamicNPIsInfectedSymptoms&lt; FP &gt;'],['../structmio_1_1osecirts_1_1DynamicNPIsInfectedSymptoms.html',1,'mio::osecirts::DynamicNPIsInfectedSymptoms&lt; FP &gt;'],['../structmio_1_1osecirvvs_1_1DynamicNPIsInfectedSymptoms.html',1,'mio::osecirvvs::DynamicNPIsInfectedSymptoms&lt; FP &gt;']]]
];
